version: '2'
services:
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=password
    extends:
      file: common.yml
      service: template
    hostname: docker-mysql
    image: mysql:5.7
    labels:
      owl: mysql
    ports:
    - 3306:3306
    restart: always
    volumes:
    - ../scripts/mysql/db_schema:/docker-entrypoint-initdb.d
    - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
  mysqltest:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/mysqltest/Dockerfile
    environment:
    - MYSQL_ROOT_PASSWORD=password
    extends:
      file: common.yml
      service: template
    hostname: docker-mysql
    labels:
      owl: mysql
    ports:
    - 3307:3306
    volumes:
    - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
  redis:
    command: redis-server /redis.conf
    extends:
      file: common.yml
      service: template-backend
    hostname: docker-redis
    image: redis:3.0
    labels:
      owl: redis
    ports:
    - 6379:6379
    restart: always
    volumes:
    - ./redis.conf:/redis.conf
  falcon-plus:
    command: bash /run.sh hbs
    image: openfalcon/falcon-plus:0.2.0
    ports:
    - 8081:8081
    restart: always
